# Generated by Django 5.0.2 on 2024-02-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripSplitApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
